spring:
  name: api
  datasource:
    postgresql:
      url: ${PG_DB_URL}
      username: ${PG_DB_USER}
      password: ${PG_DB_PWD}
      driver-class-name: org.postgresql.Driver
  
  data:
    mongodb:
      uri: ${MDB_DB_URI}
      database: makila3
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework.data.postgresql: DEBUG
    