spring:
  name: api
  datasource:
    postgresql:
      url: jdbc:postgresql://localhost:5432/sakila
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sakila_mongo
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework.data.postgresql: DEBUG
    