package org.makila.api.repository.mongodb;

import org.springframework.data.mongodb.repository.MongoRepository;
import org.makila.api.model.mongodb.OrdersEntity;

import java.time.LocalDateTime;
import java.util.List;

import org.bson.types.ObjectId;

/**
* Generated by MongoDB Relational Migrator 
* https://www.mongodb.com/products/relational-migrator 
* Collection: orders
* Language: Java
* Template: POJO
* Generated on 11/13/24

*/ 
public interface OrdersRepositoryMdb extends MongoRepository<OrdersEntity, ObjectId> {
    // List<OrdersEntity> findOrdersBetweenOrderDates(LocalDateTime minDate, LocalDateTime maxDate);
}
