package org.makila.api.repository.mongodb;


import org.springframework.data.mongodb.repository.MongoRepository;
import org.makila.api.model.mongodb.ProductsEntity;
import org.bson.types.ObjectId;

/**
* Generated by MongoDB Relational Migrator 
* https://www.mongodb.com/products/relational-migrator 
* Collection: products
* Language: Java
* Template: POJO
* Generated on 11/13/24

*/
public interface ProductsRepository extends MongoRepository<ProductsEntity, ObjectId> {
}
